version: '3.5'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis
    command: redis-server
    volumes:
      - 'redis:/data'
    ports:
      - "6379:6379"
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/ytbook
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - SECRET_KEY_BASE=production
networks:
  ytbook_default:
    external: true
volumes:
  redis:
  postgres: