require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/video_sources", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # VideoSource. As you add validations to VideoSource, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      VideoSource.create! valid_attributes
      get video_sources_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      video_source = VideoSource.create! valid_attributes
      get video_source_url(video_source)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_video_source_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      video_source = VideoSource.create! valid_attributes
      get edit_video_source_url(video_source)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new VideoSource" do
        expect {
          post video_sources_url, params: { video_source: valid_attributes }
        }.to change(VideoSource, :count).by(1)
      end

      it "redirects to the created video_source" do
        post video_sources_url, params: { video_source: valid_attributes }
        expect(response).to redirect_to(video_source_url(VideoSource.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new VideoSource" do
        expect {
          post video_sources_url, params: { video_source: invalid_attributes }
        }.to change(VideoSource, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post video_sources_url, params: { video_source: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested video_source" do
        video_source = VideoSource.create! valid_attributes
        patch video_source_url(video_source), params: { video_source: new_attributes }
        video_source.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the video_source" do
        video_source = VideoSource.create! valid_attributes
        patch video_source_url(video_source), params: { video_source: new_attributes }
        video_source.reload
        expect(response).to redirect_to(video_source_url(video_source))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        video_source = VideoSource.create! valid_attributes
        patch video_source_url(video_source), params: { video_source: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested video_source" do
      video_source = VideoSource.create! valid_attributes
      expect {
        delete video_source_url(video_source)
      }.to change(VideoSource, :count).by(-1)
    end

    it "redirects to the video_sources list" do
      video_source = VideoSource.create! valid_attributes
      delete video_source_url(video_source)
      expect(response).to redirect_to(video_sources_url)
    end
  end
end
